/**
 * TỪ ĐIỂN DỮ LIỆU — ghi chú tiếng Việt cho bảng/cột/khoá trong CSDL.
 *
 * File này là NGUỒN DUY NHẤT: khi thêm bảng/cột mới, bắt buộc thêm ghi chú
 * vào đây. Script `npm run db:comments` (tự chạy cuối `db:migrate`) sẽ:
 *   1. Gắn COMMENT ON TABLE/COLUMN vào CSDL (hiển thị trong DBeaver/pgAdmin/\d+);
 *   2. CẢNH BÁO mọi bảng/cột thực tế chưa có ghi chú → nhắc bổ sung tại đây.
 */

/** Ghi chú theo TỪNG BẢNG */
export const TABLE_COMMENTS: Record<string, string> = {
  'departments': 'Cây đơn vị tổ chức của viện (Viện → Khối → Khoa → Phòng/Ban/Tổ), hỗ trợ nhiều cấp không giới hạn',
  'job_titles': 'Danh mục chức danh (bác sĩ, điều dưỡng trưởng…) dùng khi khai báo người dùng/chữ ký',
  'users': 'Tài khoản người dùng hệ thống',
  'roles': 'Vai trò = nhóm quyền gán cho người dùng (kèm phạm vi dữ liệu OWN/DEPT/ALL)',
  'permissions': 'Danh mục quyền chi tiết theo dạng <mô-đun>.<hành-động>',
  'role_permissions': 'Quyền được gán cho từng vai trò',
  'user_roles': 'Vai trò được gán cho từng người dùng (một người có thể nhiều vai trò)',
  'user_department_scopes': 'Phạm vi khoa/phòng bổ sung cho người dùng (ngoài khoa phòng chính)',
  'audit_logs': 'Nhật ký kiểm toán toàn hệ thống: ai, làm gì, trên đối tượng nào, trước/sau',
  'login_logs': 'Nhật ký đăng nhập (thành công/thất bại, lý do, thiết bị)',
  'settings': 'Cấu hình hệ thống dạng khoá–giá trị theo nhóm',
  'notifications': 'Thông báo trong hệ thống (hiển thị ở chuông)',
  'scheduled_jobs': 'Định nghĩa tác vụ chạy định kỳ (cron): sao lưu, nhắc hạn, dọn rác…',
  'job_runs': 'Lịch sử từng lần chạy tác vụ định kỳ (thành công/thất bại, thời lượng, kết quả)',
  'data_jobs': 'Phiên nhập/xuất dữ liệu từ tệp (Excel/CSV) — theo dõi tiến độ và lỗi từng dòng',
  'attachments': 'Tệp đính kèm tải lên (ảnh chữ ký, minh chứng…)',
  'backups': 'Lịch sử các bản sao lưu CSDL',
  'utilities': 'Menu tiện ích động hiển thị theo quyền người dùng',
  'hsba_workflows': 'Quy trình ký duyệt phiếu đề nghị sửa HSBA (các bước, ai ký, hành vi khi xoá)',
  'hsba_requests': 'Phiếu đề nghị sửa hồ sơ bệnh án — luồng: tạo → KHTH duyệt → tài chính → hoàn tất',
  'hsba_signatures': 'Chữ ký xác nhận theo từng bước quy trình (kèm băm nội dung lúc ký)',
  'hsba_logs': 'Nhật ký mọi thao tác trên từng phiếu (chuyển bước, bình luận, trả lại…)',
  'hsba_comments': 'Trao đổi nội bộ trên từng phiếu — thay đổi không kinh chữ ký, xoá mềm',
  'hsba_attachments': 'Tệp minh chứng đính kèm phiếu (sổ BHYT, chứng từ…) — tệp vật lý trên ổ đĩa, xoá mềm',
  'print_templates': 'Mẫu bản in thiết kế động (khổ giấy, font, ảnh, chữ ký) dùng cho PDF/Excel/Word',
  'print_template_versions': 'Các phiên bản đã lưu của mẫu in (phục hồi khi cần)',
  'report_templates': 'Mẫu báo cáo công tác theo khoa (dòng/cột do người dùng tự thiết kế)',
  'report_sections': 'Mục (phần lớn) trong mẫu báo cáo',
  'report_blocks': 'Khối nhãn nhóm các dòng chỉ tiêu trong một mục',
  'report_rows': 'Dòng chỉ tiêu của báo cáo (kèm công thức cộng dòng nếu có)',
  'report_columns': 'Cột số liệu của báo cáo (nhập tay hoặc công thức theo cột khác)',
  'report_entries': 'Ô số liệu khoa nhập theo ngày cho từng dòng × cột',
  'report_entry_audits': 'Nhật ký thay đổi từng ô số liệu (giá trị cũ → mới, ai sửa)',
  'report_snapshots': 'Ảnh chốt số liệu theo kỳ sau khi duyệt (khoá, không sửa được)',
  'studio_dashboards': 'Trang bảng điều khiển / báo cáo tuỳ biến (Studio) — phạm vi hệ thống/vai trò/cá nhân',
  'asset_categories': 'Danh mục nhóm/loại tài sản (cây), kèm tỉ lệ khấu hao và chu kỳ kiểm định mặc định',
  'asset_locations': 'Danh mục vị trí/phòng lắp đặt thiết bị (cây), gắn khoa phòng quản lý',
  'asset_suppliers': 'Danh mục nhà cung cấp / hãng sản xuất',
  'asset_funding_sources': 'Danh mục nguồn hình thành tài sản (ngân sách, viện trợ…)',
  'assets': 'Hồ sơ tài sản: TSCĐ/CCDC, nguyên giá, khấu hao, nơi giữ, bảo hành/kiểm định',
  'asset_transactions': 'Chứng từ nghiệp vụ tài sản (ghi tăng/giảm, điều chuyển, thanh lý, sửa chữa…)',
  'asset_transaction_items': 'Từng tài sản trong chứng từ, lưu trường trước/sau thay đổi',
  'asset_events': 'Dòng thời gian sự kiện của tài sản (tạo, sửa, duyệt chứng từ, kiểm kê…)',
  'asset_depreciation_runs': 'Kỳ tính khấu hao/hao mòn (theo tháng/quý/năm, có chặn trùng kỳ)',
  'asset_depreciation_lines': 'Chi tiết khấu hao của từng tài sản trong một kỳ tính',
  'asset_inventories': 'Đợt kiểm kê tài sản (phạm vi, thành phần, kiểm kê mù, kết luận)',
  'asset_inventory_items': 'Từng tài sản trong phạm vi đợt kiểm kê: sổ sách vs thực tế, cách xử lý chênh lệch',
  'asset_inventory_scans': 'Từng lượt quét mã khi kiểm kê (kể cả quét offline đồng bộ sau — idempotent)',
  studio_subscriptions: 'Đăng ký nhận ấn bản Excel định kỳ của trang Studio (dashboard/báo cáo)',
  studio_subscription_files: 'Ấn bản Excel đã phát hành của các đăng ký Studio',
};

/** Ghi chú theo TỪNG CỘT của bảng (ưu tiên cao hơn COLUMN_COMMENTS_COMMON) */
export const COLUMN_COMMENTS: Record<string, Record<string, string>> = {
  'asset_transactions': {
    'supplier_id': 'Nhà cung cấp liên quan (ghi tăng mua mới)',
    'type': 'Loại chứng từ: ghi tăng/giảm, điều chuyển, cấp phát, thu hồi, thanh lý, sửa chữa…',
    'tx_date': 'Ngày chứng từ',
    'from_department_id': 'Khoa/phòng chuyển đi (điều chuyển/thu hồi)',
    'to_department_id': 'Khoa/phòng nhận',
    'to_location_id': 'Vị trí lắp đặt mới',
    'to_custodian_id': 'Ngườii nhận bàn giao (ID người dùng)',
    'to_custodian_name': 'Họ tên người nhận bàn giao',
    'deliverer_name': 'Người giao / người nhận (in biên bản)',
    'receiver_name': 'Đại diện bên nhận (tên hiển thị)',
    'reason': 'Lý do nghiệp vụ',
    'decision_no': 'Số quyết định / căn cứ',
    'submitted_at': 'Thờii điểm trình duyệt',
    'approved_by': 'ID người duyệt',
    'approved_at': 'Thờii điểm duyệt',
    'reject_reason': 'Lý do từ chối duyệt',
    'status': 'NHAP (nháp) | CHO_DUYET | DA_DUYET (đã áp dụng) | TU_CHOI | HUY',
    'amount': 'Giá trị thu hồi khi thanh lý / chi phí sửa chữa',
  },
  'audit_logs': {
    'entity_id': 'ID bản ghi bị tác động',
    'after_data': 'Dữ liệu sau thay đổi (JSON)',
    'action': 'Hành động: LOGIN | CREATE | UPDATE | DELETE | APPROVE | EXPORT | IMPORT | ADMIN …',
    'module': 'Phân hệ: AUTH | HSBA | REPORT | ADMIN | PRINT | UTILITY | SYSTEM',
    'entity': 'Bảng/đối tượng bị tác động',
    'description': 'Mô tả ngắn hiển thị cho người dùng',
    'before_data': 'Giá trị trước/sau khi sửa',
  },
  'backups': {
    'file_name': 'Tên tệp sao lưu',
    'file_path': 'Đường dẫn tệp trên máy chủ',
    'size_bytes': 'Dung lượng (byte)',
    'message': 'Thông báo kết quả/lỗi',
    'trigger': 'manual | scheduled',
  },
  'data_jobs': {
    'format': 'Định dạng tệp (xlsx/csv/txt)',
    'file_name': 'Tên tệp nguồn',
    'file_path': 'Đường dẫn tệp trên máy chủ',
    'file_size': 'Dung lượng (byte)',
    'total_rows': 'Tổng số dòng dữ liệu',
    'processed_rows': 'Số dòng đã xử lý',
    'failed_rows': 'Số dòng lỗi',
    'params': 'Tham số phiên nhập/xuất (JSON)',
    'message': 'Thông báo kết quả',
    'started_at': 'Thờii điểm bắt đầu',
    'finished_at': 'Thờii điểm kết thúc',
    'module': 'Phân hệ: HSBA | REPORT | USERS | DEPARTMENTS | TEMPLATES …',
    'errors': 'Chi tiết lỗi từng dòng: [{ row, message }]',
  },
  'departments': {
    'short_name': 'Tên viết tắt',
    'phone': 'Điện thoại liên hệ',
    'email': 'Thư điện tử',
    'code': 'Mã đơn vị (duy nhất) — dùng trong báo cáo, xuất/nhập dữ liệu',
    'hospital': 'Tên bệnh viện hiển thị trên báo cáo/bản in của đơn vị này',
    'report_code': 'Mã báo cáo mặc định (B4, B5…) — cấu hình được',
    'parent_id': 'Cấp trên (tự tham chiếu) — null = đơn vị gốc',
    'level': 'Cấp: 1=Viện, 2=Khối, 3=Khoa, 4=Phòng/Tổ…',
    'path': 'Đường dẫn phân cấp, ví dụ /1/4/17/ — phục vụ lọc theo nhánh cây',
    'kind': 'Loại đơn vị: KHOA | PHONG | KHOI | TRUNG_TAM | BAN — tự do khai báo',
    'head_name': 'Trưởng khoa / người phụ trách',
    'report_enabled': 'Có nhập báo cáo công tác hay không (một số phòng ban không báo cáo)',
  },
  'hsba_logs': {
    'request_id': 'Phiếu đề nghị (hsba_requests)',
    'action': 'Hành động (tạo/ký/trả lại/bình luận…)',
    'detail': 'Chi tiết thao tác (JSON)',
    'from_status': 'Trạng thái trước',
    'to_status': 'Trạng thái sau',
  },
  'hsba_comments': {
    'request_id': 'ID phiếu đề nghị trao đổi thuộc về (hsba_requests)',
    'content': 'Nội dung trao đổi (plain text)',
    'edited_at': 'Thời điểm sửa lần cuối (null = chưa sửa)',
  },
  'hsba_attachments': {
    'request_id': 'ID phiếu đề nghị tệp thuộc về (hsba_requests)',
    'file_name': 'Tên tệp gốc người dùng tải lên (không tin cậy — tham chiếu khi hiển thị)',
    'mime_type': 'Kiểu nội dung tệp (MIME type)',
    'size_bytes': 'Kích thước tệp (bytes)',
    'uploaded_by': 'ID người tải tệp (users)',
  },
  'hsba_requests': {
    'workflow_id': 'Quy trình ký áp dụng (hsba_workflows)',
    'requester_name': 'Họ tên người đề nghị',
    'requester_title': 'Chức danh người đề nghị',
    'department_name': 'Tên khoa lúc tạo phiếu (lưu cứng phục vụ bản in)',
    'patient_name': 'Họ tên bệnh nhân',
    'patient_birth_year': 'Năm sinh bệnh nhân',
    'patient_birth_date': 'Ngày sinh bệnh nhân (nếu có)',
    'patient_gender': 'Giới tính bệnh nhân',
    'patient_code': 'Mã bệnh nhân',
    'patient_address': 'Địa chỉ bệnh nhân',
    'ma_the_bhyt': 'Số thẻ BHYT',
    'ngay_vao_vien': 'Ngày vào viện',
    'ngay_ra_vien': 'Ngày ra viện',
    'reason': 'Lý do đề nghị sửa',
    'content': 'Nội dung chi tiết cần sửa',
    'attachments_note': 'Ghi chú hồ sơ kèm theo',
    'priority': 'Độ ưu tiên của phiếu',
    'return_reason': 'Lý do trả lại (bước duyệt gần nhất)',
    'returned_by': 'ID người trả lại',
    'returned_at': 'Thờii điểm trả lại',
    'completed_at': 'Thờii điểm hoàn tất phiếu',
    'search_text': 'Cột phục vụ tìm kiếm toàn văn (tự sinh)',
    'code': 'Mã phiếu: SDS-0001',
    'current_step': 'Chỉ số bước đang chờ (0-based)',
    'pending_step_key': 'Bước kế tiếp đang chờ (khoá bước)',
    'requester_id': 'Tài khoản sẽ ký với tư cách người đề nghị',
    'ma_kcb': 'Mã KCB (mã hồ sơ / mã vào viện)',
    'doi_tuong': 'Đối tượng: BHYT | VIEN_PHI | DICH_VU… tự do',
    'amount': 'Số tiền đề nghị hủy thanh toán (nếu có)',
    'extra_fields': 'Các trường tự định nghĩa thêm — cấu hình được, không cần sửa mã nguồn',
    'internal_note': 'Ghi chú nội bộ của quản trị',
    'return_count': 'Số lần bị trả lại',
    'created_at': 'Số ngày đang chờ xử lý (tính nhanh phục vụ báo cáo)',
  },
  'hsba_signatures': {
    'request_id': 'Phiếu đề nghị (hsba_requests)',
    'step_name': 'Tên bước lúc ký',
    'signed_at': 'Thờii điểm ký',
    'step_key': 'Khoá bước ký: DE_NGHI | KHTB | TAICHINH… (theo cấu hình quy trình)',
    'content_hash': 'Mã băm xác thực nội dung đã ký — chống sửa đổi sau khi ký',
  },
  'hsba_workflows': {
    'steps': 'Các bước quy trình (JSON): tên, người/vai trò ký, cho phép trả lại, câu xác nhận',
    'is_default': 'Áp dụng mặc định cho các khoa chưa gán quy trình riêng',
    'department_id': 'Áp dụng riêng cho khoa (null = dùng chung)',
  },
  'job_runs': {
    'job_id': 'Tác vụ (scheduled_jobs)',
    'job_code': 'Mã tác vụ (lưu cứng để tra nhanh)',
    'started_at': 'Thờii điểm bắt đầu chạy',
    'finished_at': 'Thờii điểm kết thúc',
    'duration_ms': 'Thờii lượng chạy (mili-giây)',
    'message': 'Thông báo kết quả',
    'error_stack': 'Dấu vết lỗi khi thất bại',
    'result': 'Kết quả trả về của handler (JSON)',
    'triggered_by': 'Ai/điều gì kích hoạt (cron/thủ công)',
    'trigger': 'queue = chạy tự động theo lịch · manual = bấm chạy ngay',
  },
  'login_logs': {
    'success': 'Đăng nhập thành công hay không',
    'reason': 'Lý do thất bại',
  },
  'notifications': {
    'body': 'Nội dung thông báo',
    'module': 'Mô-đun phát sinh',
    'entity_id': 'ID đối tượng liên quan',
    'read_at': 'Thờii điểm đã đọc (rỗng = chưa đọc)',
    'level': 'INFO | SUCCESS | WARNING | ERROR',
    'link': 'Liên kết mở khi bấm vào thông báo',
  },
  'print_template_versions': {
    'template_id': 'Mẫu in (print_templates)',
    'document': 'Toàn bộ định nghĩa mẫu tại phiên bản này (JSON)',
  },
  'print_templates': {
    'paper_size': 'Khổ giấy (A4/A5/Letter…)',
    'orientation': 'Chiều in dọc/ngang',
    'module': 'Phân hệ dùng: HSBA | REPORT | UTILITY | GENERIC',
    'doc_type': 'Loại chứng từ cụ thể: PHIEU_SUA_HSBA, BAO_CAO_TUAN…',
    'document': 'Toàn bộ định nghĩa bản in (xem PrintDocument)',
    'thumbnail': 'Ảnh xem trước (tuỳ chọn)',
    'department_id': 'Dùng chung cho mọi khoa hay riêng 1 khoa',
  },
  'report_blocks': {
    'section_id': 'Mục cha (report_sections)',
    'label': 'Nhãn khối',
    'archived': 'Đã lưu trữ (ẩn khỏi mẫu, giữ lịch sử)',
    'row_span': 'Cột gộp ô (rowspan) khi in báo cáo',
  },
  'report_columns': {
    'template_id': 'Mẫu báo cáo (report_templates)',
    'width': 'Độ rộng cột (px)',
    'align': 'Canh lề nội dung',
    'archived': 'Đã lưu trữ (ẩn khỏi mẫu, giữ lịch sử)',
    'col_key': 'Khoá cột dạng slug: hs, tq, te, dich_vu…',
    'label': 'Nhãn hiển thị: HS, TQ, TE',
    'group_label': 'Nhãn nhóm cột (ô gộp phía trên): \'BHYT\', \'Viện phí\'…',
    'kind': 'INPUT = nhập tay · CALC = tính theo công thức',
    'formula': 'Công thức cho cột CALC, ví dụ: hs+tq+te hoặc hs*2 — hỗ trợ + - * / ( ) và số',
    'format': 'Định dạng hiển thị: number | integer | percent | text',
    'summary_key': 'Cột phục vụ TỔNG HỢP TOÀN VIỆN, gán theo chỉ tiêu chuẩn: kham | vao | ra | tu_vong | hien_con | \'\'',
    'unit': 'Đơn vị tính hiển thị trên tiêu đề cột',
  },
  'report_entries': {
    'template_id': 'Mẫu báo cáo (report_templates)',
    'row_id': 'Dòng chỉ tiêu (report_rows)',
    'col_key': 'Khoá cột số liệu',
    'entry_date': 'Ngày số liệu',
  },
  'report_entry_audits': {
    'template_id': 'Mẫu báo cáo',
    'row_id': 'Dòng chỉ tiêu',
    'row_label': 'Nhãn dòng (lưu cứng)',
    'col_key': 'Khoá cột',
    'col_label': 'Nhãn cột (lưu cứng)',
    'entry_date': 'Ngày số liệu',
    'old_value': 'Giá trị cũ',
    'new_value': 'Giá trị mới',
    'action': 'create | update | delete | bulk',
  },
  'report_rows': {
    'section_id': 'Mục cha (report_sections)',
    'row_label': 'Tên chỉ tiêu',
    'is_total': 'Dòng tổng cộng (in đậm, cộng từ các dòng trên)',
    'archived': 'Đã lưu trữ (ẩn khỏi mẫu, giữ lịch sử)',
    'block_id': 'null = dòng tự do nằm trực tiếp trong mục',
    'group_label': 'Nhãn nhóm hiển thị ở cột đầu (vd: "BHYT")',
    'agg': 'Cách cộng dồn theo kỳ: SUM | FIRST | LAST | AVG | MIN | MAX',
    'unit': 'Đơn vị tính: ca, người, lượt, ngày…',
    'is_bold': 'Đánh dấu dòng tổng/tiêu đề nhóm để in đậm',
    'formula': 'Công thức ghi đè cho riêng dòng này (tùy chọn)',
  },
  'report_sections': {
    'template_id': 'Mẫu báo cáo (report_templates)',
    'note': 'Ghi chú / hướng dẫn nhập liệu hiển thị cho người nhập',
    'archived': 'Ngừng sử dụng thay vì xóa — bảo toàn toàn bộ số liệu lịch sử',
  },
  'report_snapshots': {
    'template_id': 'Mẫu báo cáo (report_templates)',
    'period_mode': 'Kiểu kỳ báo cáo (ngày/tuần/tháng/quý/năm)',
    'date_from': 'Từ ngày (kỳ báo cáo)',
    'date_to': 'Đến ngày (kỳ báo cáo)',
    'period_label': 'Nhãn kỳ hiển thị',
    'locked_at': 'Thờii điểm chốt — sau đó không sửa được',
    'payload': 'Toàn bộ số liệu đã tính tại thời điểm chốt',
    'status': 'DRAFT | APPROVED | LOCKED',
  },
  'report_templates': {
    'subtitle': 'Dòng tiêu đề phụ',
    'title': 'Tiêu đề in trên báo cáo',
    'footer_note': 'Ghi chú chân báo cáo',
    'default_period': 'Kỳ báo cáo mặc định: day | week | month | quarter | year | range',
    'print_template_id': 'Mẫu in dùng cho báo cáo này (liên kết phân hệ thiết kế bản in)',
    'layout': 'Cấu hình hiển thị bảng: độ rộng, màu, cỡ chữ…',
  },
  'role_permissions': {
    'role_id': 'Vai trò (roles)',
    'permission_id': 'Quyền (permissions)',
  },
  'roles': {
    'color': 'Màu hiển thị vai trò trên giao diện',
    'data_scope': 'Phạm vi dữ liệu mặc định của vai trò: OWN | DEPT | ALL',
    'is_system': 'Vai trò hệ thống: không cho xóa, chỉ sửa mô tả/quyền',
    'priority': 'Thứ tự ưu tiên khi hợp nhất nhiều vai trò của một người',
  },
  'scheduled_jobs': {
    'timezone': 'Múi giờ chạy cron',
    'timeout_sec': 'Giới hạn thời gian chạy (giây)',
    'max_retries': 'Số lần thử lại khi lỗi',
    'last_run_at': 'Lần chạy gần nhất',
    'last_status': 'Trạng thái lần chạy gần nhất',
    'last_error': 'Lỗi lần chạy gần nhất',
    'last_duration_ms': 'Thờii lượng lần chạy gần nhất (mili-giây)',
    'next_run_at': 'Lần chạy kế tiếp dự kiến',
    'run_count': 'Tổng số lần đã chạy',
    'fail_count': 'Tổng số lần thất bại',
    'handler': 'Tên hàm xử lý có sẵn trong hệ thống: backup.db | report.daily-digest | cache.warm …',
    'cron': 'Biểu thức cron 5 hoặc 6 trường',
    'payload': 'Tham số truyền vào hàm xử lý',
    'allow_overlap': 'Cho phép chạy chồng nếu lần trước chưa xong',
  },
  'settings': {
    'key': 'Khoá cấu hình',
    'group': 'Nhóm cấu hình',
    'label': 'Nhãn hiển thị',
    'is_public': 'Công khai — client đọc được không cần quyền',
    'value_type': 'Kiểu dữ liệu để giao diện render ô nhập: string | number | boolean | json',
  },
  'studio_dashboards': {
    'scope': 'Phạm vi trang: SYSTEM (hệ thống) / ROLE (vai trò) / PERSONAL (cá nhân)',
    'layout': 'Bố cục trang — danh sách ô widget kèm vị trí, kích thước, cấu hình truy vấn (JSON)',
    'code': 'Mã duy nhất (tự sinh hoặc tự đặt)',
    'role_code': 'Vai trò áp dụng khi scope = ROLE (mã vai trò)',
    'owner_id': 'Chủ sở hữu khi scope = PERSONAL',
    'is_default': 'Trang mặc định cho phạm vi của nó',
  },
  'user_roles': {
    'role_id': 'Vai trò (roles)',
    'granted_by': 'Người gán quyền',
  },
  'users': {
    'password_hash': 'Mật khẩu đã băm (bcrypt)',
    'email': 'Thư điện tử',
    'phone': 'Điện thoại',
    'two_factor_secret': 'Khoá bí mật xác thực 2 lớp (TOTP)',
    'locked_until': 'Khoá đăng nhập đến thời điểm này (sai mật khẩu nhiều lần)',
    'last_login_at': 'Lần đăng nhập gần nhất',
    'title': 'Chức danh: Bác sĩ, Điều dưỡng, Kế toán…',
    'department_id': 'Khoa công tác chính',
    'avatar': 'Ảnh đại diện (đường dẫn tương đối trong storage)',
    'signature_image': 'Chữ ký số dạng ảnh (base64/đường dẫn) để chèn vào bản in',
    'must_change_password': 'Bắt buộc đổi mật khẩu ở lần đăng nhập kế tiếp',
    'two_factor_enabled': 'Xác thực 2 lớp (TOTP) — bật/tắt theo người dùng',
    'failed_login_count': 'Giới hạn số lần đăng nhập sai liên tiếp',
  },
  'utilities': {
    'badge': 'Nhãn nhỏ hiển thị cạnh tên tiện ích',
    'color': 'Màu biểu tượng',
    'open_in_new_tab': 'Mở trong thẻ mới',
    'icon': 'Tên icon (lucide-react) hiển thị trên menu',
    'kind': 'BUILTIN = gắn với phân hệ có sẵn · FORM = biểu mẫu tự tạo · REPORT · LINK · IFRAME',
    'route': 'Đường dẫn giao diện (nội bộ) hoặc URL ngoài (LINK/IFRAME)',
    'config': 'Cấu hình riêng: định nghĩa trường biểu mẫu, tham số báo cáo, màu sắc…',
    'permission_code': 'Quyền cần có để thấy tiện ích này (để trống = mọi người dùng đã đăng nhập)',
    'department_ids': 'Giới hạn theo khoa (rỗng = toàn viện)',
    'placement': 'Vị trí hiển thị: sidebar | dashboard | both',
  },
  'asset_categories': {
    'group_code': 'THIET_BI_Y_TE | CNTT | NOI_THAT | PHUONG_TIEN | NHA_CUA | MAY_MOC | CCDC | KHAC',
    'code_prefix': 'Tiền tố sinh mã tài sản tự động (vd TBYT → TBYT-000123)',
    'depreciation_method': 'Phương pháp khấu hao mặc định (đường thẳng)',
    'useful_life_months': 'Thời gian sử dụng mặc định (tháng)',
    'annual_rate': 'Tỉ lệ hao mòn %/năm mặc định (TT23) — 0 = tính theo thời gian sử dụng',
    'requires_calibration': 'Có bắt buộc kiểm định/Hiệu chuẩn định kỳ không',
    'calibration_interval_months': 'Chu kỳ kiểm định (tháng)',
    'maintenance_interval_months': 'Chu kỳ bảo trì/bảo dưỡng (tháng)',
    'custom_fields': 'Thuộc tính mở rộng áp dụng cho loại: [{key,label,type,options?,required?}]',
    'path': '/1/5/12/ — truy vấn cây con nhanh',
    'kind': 'TSCD_HUU_HINH | TSCD_VO_HINH | CCDC',
  },
  'assets': {
    'category_id': 'Nhóm/loại tài sản (asset_categories)',
    'model': 'Model/ký hiệu',
    'serial_number': 'Số serial',
    'manufacturer_id': 'Hãng sản xuất (asset_suppliers)',
    'supplier_id': 'Nhà cung cấp (asset_suppliers)',
    'country_of_origin': 'Nước sản xuất',
    'year_of_manufacture': 'Năm sản xuất',
    'specifications': 'Thông số/cấu hình kỹ thuật',
    'funding_source_id': 'Nguồn hình thành chính (asset_funding_sources)',
    'funding_breakdown': 'Cơ cấu nhiều nguồn vốn: [{sourceId, amount}]',
    'acquisition_date': 'Ngày mua sắm/ghi tăng',
    'in_use_date': 'Ngày đưa vào sử dụng',
    'invoice_no': 'Số hoá đơn mua',
    'contract_no': 'Số hợp đồng mua',
    'warranty_until': 'Hạn bảo hành',
    'depreciation_method': 'Phương pháp khấu hao áp dụng',
    'useful_life_months': 'Thờii gian sử dụng (tháng)',
    'annual_rate': 'Tỉ lệ khấu hao hằng năm (%)',
    'depreciation_start_date': 'Ngày bắt đầu tính khấu hao',
    'residual_value': 'Giá trị còn lại hiện tại',
    'opening_accumulated': 'Hao mòn/khấu hao luỹ kế đầu kỳ khi chuyển đổi dữ liệu (tính đến openingDate)',
    'opening_date': 'Ngày chốt số dư đầu kỳ khi chuyển sổ',
    'accumulated_depreciation': 'Luỹ kế hiện tại = đầu kỳ + các kỳ đã chạy (cập nhật khi chốt kỳ khấu hao)',
    'last_depreciation_period': 'Kỳ khấu hao gần nhất đã tính (YYYY-MM)',
    'location_id': 'Vị trí lắp đặt (asset_locations)',
    'custodian_id': 'ID người trực tiếp giữ/sử dụng thiết bị',
    'custodian_name': 'Họ tên người trực tiếp giữ (khi không chọn từ danh sách)',
    'risk_class': '---- Trang thiết bị y tế',
    'registration_no': 'Số lưu hành/đăng ký thiết bị y tế',
    'requires_calibration': 'Có bắt buộc kiểm định/Hiệu chuẩn không',
    'calibration_interval_months': 'Chu kỳ kiểm định (tháng)',
    'last_calibration_date': 'Lần kiểm định gần nhất',
    'next_calibration_date': 'Đến hạn kiểm định',
    'maintenance_interval_months': 'Chu kỳ bảo trì/bảo dưỡng (tháng)',
    'last_maintenance_date': 'Lần bảo trì gần nhất',
    'next_maintenance_date': 'Đến hạn bảo trì',
    'attributes': 'Thuộc tính mở rộng theo nhóm tài sản (JSON)',
    'tags': 'Nhãn phân loại tự do (JSON)',
    'image_url': 'Ảnh tài sản',
    'search_text': 'Chuỗi tìm kiếm không dấu (mã, tên, serial, model, khoa, vị trí…)',
    'last_inventory_at': 'Lần kiểm kê gần nhất (tự cập nhật khi duyệt đợt)',
    'barcode': 'Mã vạch/QR in trên tem — mặc định bằng mã tài sản, có thể dùng mã cũ khi chuyển đổi dữ liệu',
    'kind': 'TSCD_HUU_HINH | TSCD_VO_HINH | CCDC — sao từ loại, cho phép ghi đè',
    'original_cost': '---- Tài chính',
    'status': '---- Quản lý sử dụng',
    'condition': 'TOT | KHA | TRUNG_BINH | KEM | HONG',
    'parent_id': 'Tài sản cha (linh kiện/phụ kiện đi kèm)',
  },
  'asset_transaction_items': {
    'transaction_id': 'Chứng từ (asset_transactions)',
    'asset_id': 'Tài sản (assets)',
    'before': 'Ảnh chụp trạng thái trước/sau khi duyệt',
    'after': 'Trường thay đổi sau chứng từ (JSON)',
    'condition': 'Tình trạng tài sản tại thời điểm chứng từ',
    'amount': 'Đánh giá lại: nguyên giá mới · thanh lý: giá bán từng tài sản · sửa chữa: chi phí',
  },
  'asset_events': {
    'asset_id': 'Tài sản (assets)',
    'event_type': 'CREATE | UPDATE | TX_<type> | DEPRECIATION | LABEL | INVENTORY | MAINTENANCE …',
    'detail': 'Chi tiết sự kiện (JSON)',
    'transaction_id': 'Chứng từ liên quan nếu có',
    'user_name': 'Ngườii thực hiện (tên hiển thị)',
  },
  'asset_depreciation_runs': {
    'period_type': 'MONTHLY | YEARLY',
    'asset_count': 'Số tài sản đã tính trong kỳ',
    'total_amount': 'Tổng tiền khấu hao của kỳ',
    'created_by_name': 'Ngườii chạy kỳ tính (tên hiển thị)',
    'period': 'YYYY-MM (tháng) hoặc YYYY (năm — hao mòn TT23)',
    'status': 'DA_CHOT | DA_HUY',
  },
  'asset_depreciation_lines': {
    'run_id': 'Kỳ tính khấu hao (asset_depreciation_runs)',
    'asset_id': 'Tài sản (assets)',
    'method': 'Phương pháp khấu hao áp dụng cho dòng này',
    'cost_basis': 'Nguyên giá/giá trị làm căn cứ tính',
    'accumulated_before': 'Luỹ kế trước kỳ',
    'accumulated_after': 'Luỹ kế sau kỳ',
    'book_value_after': 'Giá trị còn lại sau kỳ',
    'category_id': 'Nhóm tài sản (để cộng nhanh báo cáo)',
  },
  'asset_inventories': {
    'scope': 'Phạm vi kiểm kê (khoa/vị trí/nhóm/loại — JSON)',
    'planned_date': 'Ngày dự kiến kiểm kê',
    'snapshot_at': 'Thời điểm chốt sổ sách (ngày kiểm kê trên biên bản)',
    'finished_at': 'Thờii điểm kết thúc quét (khoá số liệu)',
    'completed_at': 'Thờii điểm duyệt hoàn tất đợt',
    'decision_no': 'Số quyết định thành lập hội đồng kiểm kê',
    'committee': 'Thành phần hội đồng kiểm kê (JSON)',
    'member_ids': 'Tài khoản được phân công quét (ngoài người có quyền quản lý kiểm kê)',
    'blind': 'Kiểm kê "mù": người quét không thấy danh sách dự kiến / tình trạng sổ sách',
    'conclusion': 'Kết luận kiểm kê',
    'created_by_name': 'Ngườii lập đợt (tên hiển thị)',
    'approved_by': 'ID người duyệt kết quả',
    'approved_by_name': 'Ngườii duyệt kết quả (tên hiển thị)',
    'status': 'NHAP | DANG_KIEM_KE | CHO_DUYET | HOAN_TAT | DA_HUY',
  },
  'asset_inventory_items': {
    'inventory_id': 'Đợt kiểm kê (asset_inventories)',
    'asset_id': 'null = quét được mã không có trong hồ sơ (tài sản thừa chưa có hồ sơ)',
    'scanned_code': 'Mã đã quét khớp dòng này',
    'expected': 'true = có trong sổ sách của phạm vi kiểm kê; false = phát hiện thêm khi quét',
    'book_department_id': '---- Sổ sách tại thời điểm chốt',
    'book_location_id': 'Vị trí theo sổ sách',
    'book_custodian_name': 'Ngườii giữ theo sổ sách',
    'book_status': 'Trạng thái sử dụng theo sổ sách',
    'book_condition': 'Tình trạng theo sổ sách',
    'book_cost': 'Nguyên giá theo sổ sách',
    'book_value': 'Giá trị còn lại theo sổ sách',
    'check_state': 'CHUA_KIEM | CO (thấy) | KHONG_THAY (xác nhận không thấy)',
    'actual_department_id': 'Khoa/phòng thực tế khi quét',
    'actual_location_id': 'Vị trí thực tế khi quét',
    'actual_condition': 'Tình trạng thực tế khi quét',
    'result': 'KHOP | SAI_VI_TRI | SAI_TINH_TRANG | THIEU | THUA | KHONG_RO | \'\' (chưa kiểm)',
    'scan_count': 'Số lần quét vào dòng này',
    'method': 'CAMERA | SCANNER | MANUAL | OFFLINE',
    'checked_at': 'Thờii điểm xác nhận dòng',
    'checked_by': 'ID người xác nhận',
    'checked_by_name': 'Ngườii xác nhận (tên hiển thị)',
    'resolution': 'Xử lý chênh lệch: DIEU_CHUYEN | BAO_MAT | BAO_HONG | GHI_NHAN (chấp nhận, không lập chứng từ)',
    'resolution_tx_id': 'Chứng từ xử lý chênh lệch đã lập',
  },
  'asset_inventory_scans': {
    'inventory_id': 'Đợt kiểm kê (asset_inventories)',
    'client_id': 'ID lượt quét phía client — chống ghi trùng khi đồng bộ offline (idempotent)',
    'item_id': 'Dòng kiểm kê khớp được (có thể rỗng nếu mã lạ)',
    'outcome': 'FOUND | DUPLICATE | EXTRA | UNKNOWN',
    'method': 'camera/máy quét/nhập tay',
    'location_id': 'Vị trí quét nếu chọn',
    'user_name': 'Ngườii quét (tên hiển thị)',
    'device_id': 'Định danh thiết bị quét',
    'scanned_at': 'Thờii điểm quét trên thiết bị (có thể khác giờ máy chủ khi offline)',
  },
  'asset_suppliers': {
    'roles': 'Vai trò: NCC (nhà cung cấp) · HANG_SX (hãng sản xuất) · BAO_TRI (đơn vị bảo trì/kiểm định) — có thể nhiều',
    'tax_code': 'Mã số thuế',
    'address': 'Địa chỉ',
    'phone': 'Điện thoại',
    'email': 'Thư điện tử',
    'contact_name': 'Ngườii liên hệ',
    'country': 'Quốc gia',
  },
  'attachments': {
    'module': 'Phân hệ sở hữu: HSBA | REPORT | UTILITY',
    'owner_id': 'Bản ghi sở hữu',
    'file_name': 'Tên tệp trên đĩa',
    'original_name': 'Tên tệp gốc khi tải lên',
    'mime_type': 'Kiểu nội dung (MIME)',
    'size': 'Dung lượng (byte)',
    'checksum': 'Mã băm kiểm tra toàn vẹn tệp',
    'uploaded_by': 'ID người tải lên',
    'path': 'Đường dẫn tương đối trong thư mục lưu trữ',
  },
  'permissions': {
    'code': 'Mã quyền dạng module.action: hsba.request.create',
    'module': 'Nhóm nghiệp vụ: hsba | report | admin | system | print …',
    'action': 'Thao tác: view | create | update | delete | approve | sign | export | admin',
    'is_system': 'Quyền hệ thống: không cho xóa khỏi danh mục',
  },
  'asset_locations': {
    'kind': 'KHU | TOA_NHA | TANG | PHONG | KHO | KHAC',
  },

  studio_subscriptions: {
    _table: 'Đăng ký nhận ấn bản Excel định kỳ của trang Studio',
    id: 'Khoá chính',
    page_id: 'Trang Studio (FK studio_dashboards)',
    user_id: 'Người nhận ấn bản (FK users) — dữ liệu render theo quyền người này',
    label: 'Tên gợi nhớ của đăng ký',
    frequency: 'Tần suất: DAILY (hằng ngày) | WEEKLY (thứ Hai) | MONTHLY (mùng 1)',
    hour_of_day: 'Giờ phát hành (giờ máy chủ, 0–23)',
    active: 'Còn hiệu lực không',
    last_run_at: 'Lần phát hành gần nhất',
    next_run_at: 'Lần phát hành kế tiếp (tác vụ rà theo cột này)',
    last_status: 'Kết quả lần chạy cuối: PENDING | SUCCESS | FAILED',
    last_error: 'Thông điệp lỗi lần chạy cuối',
    run_count: 'Số lần đã phát hành thành công',
    created_at: 'Ngày tạo',
    updated_at: 'Cập nhật cuối',
  },

  studio_subscription_files: {
    _table: 'Ấn bản Excel đã phát hành của các đăng ký Studio',
    id: 'Khoá chính',
    subscription_id: 'Đăng ký sở hữu (FK studio_subscriptions)',
    user_id: 'Chủ nhân file (FK users)',
    page_id: 'Trang Studio nguồn',
    page_name: 'Tên trang tại thờI điểm xuất',
    file_name: 'Tên tệp Excel',
    file_path: 'Đường dẫn tương đối trong thư mục kết xuất',
    size_bytes: 'Kích thước tệp (byte)',
    trigger: 'Nguồn phát hành: queue (theo lịch) | manual (chạy thử)',
    created_at: 'Thời điểm xuất',
  },
};

/** Ghi chú CHUNG theo tên cột — áp dụng cho mọi bảng khi cột chưa có ghi chú riêng */
export const COLUMN_COMMENTS_COMMON: Record<string, string> = {
  id: 'Khoá chính tự tăng',
  code: 'Mã duy nhất',
  name: 'Tên',
  title: 'Tiêu đề / chức danh',
  description: 'Mô tả',
  note: 'Ghi chú',
  active: 'Đang hoạt động (false = ngừng)',
  sort_order: 'Thứ tự sắp xếp hiển thị',
  created_at: 'Thời điểm tạo',
  updated_at: 'Thời điểm cập nhật cuối',
  deleted_at: 'Thời điểm xoá mềm (rỗng = còn hiệu lực)',
  created_by: 'ID người tạo',
  updated_by: 'ID người cập nhật cuối',
  parent_id: 'Bản ghi cha (rỗng = gốc)',
  level: 'Cấp trong cây phân cấp',
  path: 'Đường dẫn phân cấp dạng /id/id/ — lọc theo nhánh cây',
  kind: 'Loại / kiểu',
  status: 'Trạng thái',
  user_id: 'ID người dùng thực hiện',
  username: 'Tên đăng nhập',
  full_name: 'Họ và tên',
  department_id: 'Khoa/phòng phụ trách',
  ip: 'Địa chỉ IP thao tác',
  user_agent: 'Trình duyệt / thiết bị thao tác',
  amount: 'Số tiền (đồng)',
  value: 'Giá trị',
  unit: 'Đơn vị tính',
  quantity: 'Số lượng',
  payload: 'Nội dung dạng JSON',
  version: 'Số phiên bản',
  is_default: 'Là bản mặc định',
};
